### ISSUE TITLE
Update of new version 2015-10-05 not possible

### ISSUE THREAD

**Issue by bobcanthelpyou** [turnermm/newpagetemplate#1]
Running Update at the Extension Manager (Dokuwiki Hrun) doesn't update the plugin

* run Update

![bildschirmfoto von 2015-10-21 03 26 13](https://cloud.githubusercontent.com/assets/4523264/10626035/7026ba5e-77ab-11e5-982f-d2ee59ff2d05.png)

* Shows success

![bildschirmfoto von 2015-10-21 03 38 40](https://cloud.githubusercontent.com/assets/4523264/10626028/5b54a6d6-77ab-11e5-8bea-7dd76871d761.png)

* Update still available

![bildschirmfoto von 2015-10-21 03 26 13](https://cloud.githubusercontent.com/assets/4523264/10626035/7026ba5e-77ab-11e5-982f-d2ee59ff2d05.png)

Is it a problem of the Dokuwiki? A problem of GitHub? The plugin? Something else?
https://www.dokuwiki.org/plugin:newpagetemplate

**Comment by turnermm** [comment]
Sorry for the inconvenience.  I had updated the date on the dokuwiki.org plugin page, but for some reason the updated info file was not uploaded from my server to github (even though the log on my server shows that it had been).  There were no other changes apart from the new date, which is needed so that users know that the plugin will work with current versions of dokuwiki.

**Comment by bobcanthelpyou** [comment]
Thx that fixed it :)
